name: Deploy to staging

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy everything to staging cluster
    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
      - name: ssh and Deploy Everything
        run: |
            ssh -i ~/ssh_key -o StrictHostKeyChecking=yes -o ServerAliveInterval=60 ubuntu@16.171.249.33 << 'EOF'
            cd /home/ubuntu/code-twins || exit 1
            ls /home/ubuntu/code-twins
            git pull origin main 
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 23
            pnpm install
            pnpm run build
            pm2 restart all 
            EOF