name: Deploy to staging

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy everything to staging cluster
    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: ssh and Deploy Everything
        run: |
            ssh -i ~/ssh_key -o StrictHostKeyChecking=yes ubuntu@16.171.249.33 << 'EOF'
            cd ./code-twins
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart all 
            EOF